//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProgramming_Class_i.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int Id { get; set; }
    }
}
