//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProgramming_Class_i.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStaff
    {
        public int ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public bool Full_Time { get; set; }
        public System.DateTime Hire_Date { get; set; }
        public decimal Salary { get; set; }
    }
}
